if(MSVC)
  add_compile_options(
    $<$<CONFIG:Debug>:/Od>
    $<$<CONFIG:Debug>:/Zi>
    $<$<CONFIG:Release>:/w>
    $<$<CONFIG:Release>:/O2>)
else()
  add_compile_options(
    $<$<CONFIG:Debug>:-pedantic>
    $<$<CONFIG:Debug>:-Wall>
    $<$<CONFIG:Debug>:-Wextra>
    $<$<CONFIG:Debug>:-Wconversion>
    $<$<CONFIG:Debug>:-Wsign-conversion>
    $<$<CONFIG:Debug>:-Wno-unused-but-set-parameter>
    $<$<CONFIG:Debug>:-O0>
    $<$<CONFIG:Debug>:-g3>
    $<$<CONFIG:Debug>:-fsanitize=address>
    $<$<CONFIG:Debug>:-fsanitize=undefined>
    $<$<CONFIG:Release>:-w>
    $<$<CONFIG:Release>:-O3>
    $<$<CONFIG:Release>:-flto>)

add_link_options(
    $<$<CONFIG:Debug>:-fsanitize=address>
    $<$<CONFIG:Debug>:-fsanitize=undefined>
    $<$<CONFIG:Release>:-flto>)
endif()